version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 231726701291.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=231726701291.dkr.ecr.ap-south-1.amazonaws.com/aws-project
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Build started
      - docker build -t aws-project .
      - docker tag aws-project:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"aws-project-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
