version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 231726701291.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t my-app .
      - docker tag my-app:latest 231726701291.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
  post_build:
    commands:
      - docker push 231726701291.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
      - printf '[{"name":"my-app","imageUri":"%s"}]' 231726701291.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
